2025-06-15 11:05:21,537 ERROR: Erreur interne du serveur (500): 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in X:\MediaManagerSuite\app\__init__.py:118]
Traceback (most recent call last):
  File "X:\MediaManagerSuite\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "X:\MediaManagerSuite\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "X:\MediaManagerSuite\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "X:\MediaManagerSuite\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "X:\MediaManagerSuite\app\__init__.py", line 23, in decorated_function
    return f(*args, **kwargs)
  File "X:\MediaManagerSuite\app\config_ui\routes.py", line 24, in show_config
    return render_template('configuration.html',
                           title="Configuration de l'Application",
                           params=params_list)
  File "X:\MediaManagerSuite\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "X:\MediaManagerSuite\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "X:\MediaManagerSuite\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "X:\MediaManagerSuite\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "X:\MediaManagerSuite\app\templates\configuration.html", line 48, in top-level template code
    <a class="nav-link" href="{{ url_for('config_ui.logout') }}">Déconnexion (Config)</a>
    
  File "X:\MediaManagerSuite\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\MediaManagerSuite\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "X:\MediaManagerSuite\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'config_ui.logout'. Did you mean 'config_ui.static' instead?
2025-06-15 11:05:21,885 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:12:30,805 INFO: MediaManagerSuite startup in production mode [in X:\MediaManagerSuite\app\__init__.py:48]
2025-06-15 11:12:31,212 INFO: Blueprint 'plex_editor' enregistré avec succès. [in X:\MediaManagerSuite\app\__init__.py:59]
2025-06-15 11:12:31,362 INFO: Blueprint 'seedbox_ui' enregistré avec succès. [in X:\MediaManagerSuite\app\__init__.py:64]
2025-06-15 11:12:31,366 INFO: Blueprint 'config_ui' enregistré avec succès. [in X:\MediaManagerSuite\app\__init__.py:72]
2025-06-15 11:12:31,367 INFO: Application MediaManagerSuite créée et configurée. [in X:\MediaManagerSuite\app\__init__.py:122]
2025-06-15 11:12:31,367 INFO: Démarrage MediaManagerSuite. Debug: False, Reloader: False (pour test) [in X:\MediaManagerSuite\run.py:25]
2025-06-15 11:12:39,265 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:12:55,760 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:12:57,979 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:12:59,022 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:12:59,356 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:13:00,838 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:13:01,614 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:13:01,946 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:13:02,378 INFO: Index: Construction de l'arborescence pour le dossier de staging: X:/seedbox_staging [in X:\MediaManagerSuite\app\seedbox_ui\routes.py:1516]
2025-06-15 11:13:02,807 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:13:05,208 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:13:05,540 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:31:20,343 INFO: MediaManagerSuite startup in production mode [in X:\MediaManagerSuite\app\__init__.py:48]
2025-06-15 11:31:20,751 INFO: Blueprint 'plex_editor' enregistré avec succès. [in X:\MediaManagerSuite\app\__init__.py:59]
2025-06-15 11:31:20,900 INFO: Blueprint 'seedbox_ui' enregistré avec succès. [in X:\MediaManagerSuite\app\__init__.py:64]
2025-06-15 11:31:20,904 INFO: Blueprint 'config_ui' enregistré avec succès. [in X:\MediaManagerSuite\app\__init__.py:72]
2025-06-15 11:31:20,905 INFO: Application MediaManagerSuite créée et configurée. [in X:\MediaManagerSuite\app\__init__.py:122]
2025-06-15 11:31:20,905 INFO: Démarrage MediaManagerSuite. Debug: False, Reloader: False (pour test) [in X:\MediaManagerSuite\run.py:25]
2025-06-15 11:31:26,249 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:40:08,647 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:40:11,103 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:40:11,384 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:40:12,228 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:40:13,385 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:40:13,743 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:40:17,107 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/.well-known/appspecific/com.chrome.devtools.json (Référent: None) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 11:43:55,499 INFO: Index: Construction de l'arborescence pour le dossier de staging: X:/seedbox_staging [in X:\MediaManagerSuite\app\seedbox_ui\routes.py:1516]
2025-06-15 11:51:02,317 WARNING: Erreur 404 - Page non trouvée: http://localhost:5001/favicon.ico (Référent: http://localhost:5001/login) [in X:\MediaManagerSuite\app\__init__.py:113]
2025-06-15 12:38:52,257 INFO: MediaManagerSuite startup in production mode [in X:\MediaManagerSuite\app\__init__.py:48]
2025-06-15 12:38:52,684 INFO: Blueprint 'plex_editor' enregistré avec succès. [in X:\MediaManagerSuite\app\__init__.py:59]
2025-06-15 12:38:53,042 INFO: Blueprint 'seedbox_ui' enregistré avec succès. [in X:\MediaManagerSuite\app\__init__.py:64]
2025-06-15 12:38:53,047 INFO: Blueprint 'config_ui' enregistré avec succès. [in X:\MediaManagerSuite\app\__init__.py:72]
2025-06-15 12:38:53,049 INFO: Application MediaManagerSuite créée et configurée. [in X:\MediaManagerSuite\app\__init__.py:122]
2025-06-15 12:38:53,049 INFO: Démarrage MediaManagerSuite. Debug: False, Reloader: False (pour test) [in X:\MediaManagerSuite\run.py:25]
2025-06-15 12:39:01,476 INFO: Utilisateur 'User' (ID: 36440265) sélectionné. [in X:\MediaManagerSuite\app\plex_editor\routes.py:76]
2025-06-15 12:39:06,262 INFO: show_library: Arguments finaux pour API search(): {'sort': 'addedAt:desc'} [in X:\MediaManagerSuite\app\plex_editor\routes.py:226]
2025-06-15 12:39:06,885 INFO: Emprunt d'identité réussi pour 'User'. [in X:\MediaManagerSuite\app\plex_editor\routes.py:248]
